### ISSUE TITLE
New update problem

### ISSUE THREAD

**Issue by Xarano-GIT** [bjoerns1983/Emby.Plugin.TelegramNotification#10] opened 2022-12-24 18:56 UTC
Hi, 

I updated my plugin to the new version just released.
I'm on Emby 4.8.0.21 Beta

Afterwards, I am not able to configure notifications anymore.
The plugin page itself says it now has no configurations available which I assume is part of the new 4.8 system.

However when I try to add the plugin on the notifications page, it simply does not appear.

![image](https://user-images.githubusercontent.com/45671929/209448239-c8660b1c-8a10-4839-9fb8-fb945c7c9d41.png)

Is this an Emby problem, or an issue with the plugin? Or am I doing something silly?

Thanks!

**Comment by bjoerns1983** [comment] 2022-12-24 19:08
To be honest i dont know.
I just merged Lukes changes and had no chance to test it till now.

Also i will not have a look after it during the holidays.

**Comment by Krocko** [comment] 2022-12-28 15:18
Same here.

**Comment by Krocko** [comment] 2023-01-11 11:36
@bjoerns1983 any news?

**Comment by bjoerns1983** [comment] 2023-01-11 12:42
Not really, only thing i know that the same happens on my Dev Setup with the official E-Mail plugin.
So i really dont know if it is caused by the Plugin or if it is a bug with the Server.

From the Log i can see that the Plugin loads and i dont see any errors there.

I will have to wait for @LukePulverenti answer on the Forum.

**Comment by LukePulverenti** [comment] 2023-01-11 19:09
> Hi,
> 
> I updated my plugin to the new version just released. I'm on Emby 4.8.0.21 Beta
> 
> Afterwards, I am not able to configure notifications anymore. The plugin page itself says it now has no configurations available which I assume is part of the new 4.8 system.
> 
> However when I try to add the plugin on the notifications page, it simply does not appear.
> 
> ![image](https://user-images.githubusercontent.com/45671929/209448239-c8660b1c-8a10-4839-9fb8-fb945c7c9d41.png)
> 
> Is this an Emby problem, or an issue with the plugin? Or am I doing something silly?
> 
> Thanks!

What exactly doesn't appear? It says Telegram right in your screenshot, right?

**Comment by bjoerns1983** [comment] 2023-01-11 19:50
When you click on Telegram Icon there simply nothing happens.
Compared to the EMail Plugin i would assume a Page should open where you can set the Chat-ID Bot Token etc.

**Comment by LukePulverenti** [comment] 2023-01-11 20:05
OK please try the latest code. Thanks.

**Comment by bjoerns1983** [comment] 2023-01-11 20:17
Works, will upload the working DLL in a couple of minutes. Thanks @LukePulverenti

**Comment by Krocko** [comment] 2023-01-12 16:34
This don‘t work on safari browser (iOS and also macOS). The settings popup don‘t open. 
Chrome browser is working. 
Any chance to get this working on safari?

Edit: Chrome browser is only working on macOS. 
Chrome browser on iOS also don't work.

**Comment by bjoerns1983** [comment] 2023-01-14 13:27
Please before you post an issue here test if the issue is the same with the EMail Plugin, which is done by the Emby dev's.
I have tested it and the config dialog also does not open there using Safari on iOS.

So it must be a problem between the webkit engine and Emby Core.
On iOS webkit is mandatory for all browsers.

**Closed as completed** 2023-01-14 13:27 UTC

**Comment by Krocko** [comment] 2023-01-14 13:47
Will do. 
Thank you for confirming.
